---
namespace: staging
replicas:
  - name: nginx-deployment
    count: 2
images:
  - name: 009160067324.dkr.ecr.me-south-1.amazonaws.com/misc/devops
    newTag: v0.1.0
resources:
  - ../../../my-app-base
